
name: Merge M3U playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC, optional

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Playlist 1
      run: curl -s -o playlist1.m3u "https://raw.githubusercontent.com/mmtech255/test/refs/heads/main/Tataplay.php"

    - name: Download Playlist 2
      run: curl -s -o playlist2.m3u "https://raw.githubusercontent.com/mmtech255/test/refs/heads/main/Hotstar.php"

    - name: Merge playlists
      run: |
        echo "#EXTM3U" > combined.m3u
        grep -v "^#EXTM3U" playlist1.m3u >> combined.m3u
        grep -v "^#EXTM3U" playlist2.m3u >> combined.m3u

    - name: Commit and push combined playlist
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add combined.m3u
        git commit -m "Update combined playlist"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
